"""Bake the supplied SVG dot map for a single, inexpensive Flutter painter.

Run from any directory: python tool/generate_world_map.py [--check].
SVG originals are the source of truth. Each dot has a solid cubic path and a
0.01-unit outline; do not render those as two independently animated dots.
This deliberately validates this export format rather than parsing arbitrary SVG.
"""
import hashlib
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / 'assets/images/SVG' / f'bg-{theme}_1.svg' for theme in ('dark', 'light')]
NUMBER = r'[-+]?(?:\d*\.\d+|\d+)'

def read_map(path):
    root = ET.parse(path).getroot()
    paths = [e.attrib['d'] for e in root.iter() if e.tag.endswith('}path')]
    if len(paths) % 2:
        raise ValueError('Expected solid/outline pairs')
    points = []
    for solid, outline in zip(paths[::2], paths[1::2]):
        match = re.match(r'^M(' + NUMBER + r'),(' + NUMBER + r')c', solid)
        if not match:
            raise ValueError(f'Unsupported dot path: {solid}')
        x, y = map(float, match.groups())
        cubic = re.findall(NUMBER, solid[match.end():])[:6]
        if len(cubic) != 6:
            raise ValueError('Missing first cubic')
        rx, ry = map(float, cubic[-2:])
        if not (3.83 <= rx <= 3.87 and 3.83 <= ry <= 3.87):
            raise ValueError('Non-circular or unexpected dot size')
        ox, oy = map(float, re.findall(NUMBER, outline)[:2])
        if abs(x-ox) > .03 or abs(y-oy) > .03 or 'Z' not in outline:
            raise ValueError('Outline does not match its dot')
        points.append((x, round(y+ry, 2)))
    if len(set(points)) != len(points):
        raise ValueError('Duplicate centers')
    style = next(e.text for e in root.iter() if e.tag.endswith('}style'))
    color = re.search(r'fill:\s*#([0-9a-fA-F]{6})', style).group(1).upper()
    return root.attrib['viewBox'], paths, points, color

maps = [read_map(p) for p in SOURCES]
if maps[0][:3] != maps[1][:3]:
    raise ValueError('Theme SVGs have different geometry; regenerate deliberately')
view = list(map(float, maps[0][0].split()))
if view[:2] != [0, 0]:
    raise ValueError('Expected zero-origin viewBox')
lines = ['// GENERATED by tool/generate_world_map.py. Do not edit.',
         '// Source SVGs remain canonical; solid/outline pairs form one dot.']
for source in SOURCES:
    lines.append(f'// {source.name} SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}')
lines += ["import 'package:flutter/painting.dart';", '',
          f'const worldMapSize = Size({view[2]}, {view[3]});',
          'const worldMapDotRadius = 3.86;',
          f'const worldMapDarkColor = Color(0xFF{maps[0][3]});',
          f'const worldMapLightColor = Color(0xFF{maps[1][3]});',
          'const worldMapPoints = <Offset>[']
lines += [f'  Offset({x:g}, {y:g}),' for x,y in maps[0][2]]
lines += ['];', '']
output = ROOT / 'lib/features/home/model/world_map_geometry.dart'
text = '\n'.join(lines)
if '--check' in sys.argv:
    if not output.exists() or output.read_text(encoding='utf-8') != text:
        raise SystemExit('Generated map is stale; run tool/generate_world_map.py')
else:
    output.write_text(text, encoding='utf-8')
print(f'{len(maps[0][2])} dots, matched both SVG themes; {output.name}')
