// Run with Node.js (full ICU): node tool/generate_server_country_names.mjs
// Uses the same Intl.DisplayNames API as zeon-server/server-naming.ts.
// Generated country names are checked in; the application makes no lookup requests.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const locales = ['en', 'ru', 'ar', 'es', 'fa', 'fr', 'id', 'pt-BR', 'tr', 'zh-CN', 'zh-TW'];
const names = Object.fromEntries(locales.map(locale => [locale, new Intl.DisplayNames([locale], {
  type: 'region', fallback: 'none',
})]));
const codes = [];
for (let a = 65; a <= 90; a++) {
  for (let b = 65; b <= 90; b++) {
    const code = String.fromCharCode(a, b);
    if (new Intl.Locale(`und-${code}`).region === code && names.en.of(code) && names.ru.of(code)) codes.push(code);
  }
}
for (const locale of locales) {
  const file = path.join(root, `assets/translations/${locale}.i18n.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  data.pages.proxies.serverNames = {
    fast: locale === 'ru' ? 'БЫСТРЫЙ' : 'FAST',
    bypass: locale === 'ru' ? 'СВЯЗЬ' : 'BYPASS',
    'countries(map)': Object.fromEntries(codes.map(code => {
      const value = names[locale].of(code);
      if (!value) throw new Error(`Missing country name: ${locale}/${code}`);
      return [code, value];
    })),
  };
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
}
const aliases = Object.fromEntries(codes.map(code => [names.ru.of(code).toLowerCase(), code]));
// Explicit abbreviations and no-flag hints used by the server, plus common
// Russian variants from existing/imported subscriptions.
Object.assign(aliases, {
  'сша': 'US', 'оаэ': 'AE', 'корея': 'KR', 'южная корея': 'KR',
  'голландия': 'NL', 'чешская республика': 'CZ', 'белоруссия': 'BY',
  'российская федерация': 'RU', 'великобритания': 'GB',
  'соединенные штаты': 'US', 'соединённые штаты': 'US',
  'соединенные штаты америки': 'US', 'соединённые штаты америки': 'US',
  'объединенные арабские эмираты': 'AE', 'объединённые арабские эмираты': 'AE',
  'неизвестно': 'ZZ',
});
const quote = value => "'" + value.replaceAll('\\', '\\\\').replaceAll("'", "\\'") + "'";
const dart = [
  '// Generated by tool/generate_server_country_names.mjs.',
  `// Source: Node Intl.DisplayNames / ICU ${process.versions.icu}.`,
  '// Recognition data only; display translations live in assets/translations.',
  'const russianServerCountryCodes = <String, String>{',
  ...Object.entries(aliases).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)
    .map(([name, code]) => `  ${quote(name)}: ${quote(code)},`),
  '};', '',
].join('\n');
fs.writeFileSync(path.join(root, 'lib/features/proxy/model/server_country_names.dart'), dart);
console.log(`Generated ${codes.length} country/region names in ${locales.length} locales; ${Object.keys(aliases).length} Russian aliases.`);
